name: workflow 

on:
  push:
    branches: 
        - main 
    paths-ignore:
        - 'README.md'


jobs: 
    intergration:
        name: Continous Integration
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Lint code 
          run: echo "Linting repository"

        - name: Build Docker image
          run: echo "Building Docker image"

    build-and-push-ecr-image:
        name: Continous Delivery
        runs-on: ubuntu-latest
        needs: intergration
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Check AWS CLI
          run: aws --version

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
          with:
            mask-password: true

        - name: Build and push Docker image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORTY_NAME }}
            IMAGE_TAG: latest

          run: |
            # Build a docer container and 
            # push it to Amazon ECR so that i can 
            # be deployed to AWS ECS or AWS EKS
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "Docker image pushed to Amazon ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    Continous_Deployment:
       name: Continous Deployment
       runs-on: self-hosted
       steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login  to AWS ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Pull Docker image from Amazon ECR
          run:
            docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORTY_NAME }}:latest

        # - name : stop and remove container if running 
        #   run: |
        #     if [ $(docker ps -q -f name=network-security-app) ]; then
        #       docker stop network-security-app
        #       docker rm network-security-app
        #     fi    

        - name: Run Docker Image to serve users 
          run: |
            docker run -d -p 8000:8000 --ipc="host" --name = networksecurity -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORTY_NAME }}:latest
        - name: Clean previous images and containers
          run: |
            docker system prune -f 